# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
# user = CreateAdminService.new.call
# puts 'CREATED ADMIN USER: ' << user.email
# Environment variables (ENV['...']) can be set in the file .env file.

titan = House::Titan.create(name: 'Titans', playable: false, leader: 'The Oraculum of Time')
empire = House::Empire.create(name: 'Empire', playable: false, leader: 'Emperor')
rene = House::Renegat.create(name: 'Renegates', playable: false, leader: '')
atr = House::Atreides.create(name: 'Atreides', playable: true, leader: 'Duke')
har = House::Harkonnen.create(name: 'Harkonnen', playable: true, leader: 'Baron')
cor = House::Corrino.create(name: 'Corrino', playable: true, leader: 'Padishah')

p 'House done'

System.create(name: 'Aclin Neutra')
System.create(name: 'Delphinus')
System.create(name: 'Anbus')
System.create(name: 'Aclin Beta')
System.create(name: 'Eridani C')
System.create(name: 'Mu Draconis')
System.create(name: 'Atari')
System.create(name: 'Balút')
System.create(name: 'Barandik')
System.create(name: 'Kuentsing')
System.create(name: 'Alastria')
System.create(name: 'Norma Cenva')
System.create(name: 'Buzell Alpha')
System.create(name: 'Beakkal Centa')
System.create(name: 'Alpha Centauri A')
System.create(name: 'Eridani B')
System.create(name: 'Cerbol Leta')
System.create(name: 'Danu')
System.create(name: 'Dur')
System.create(name: 'Alpha Centauri B')
System.create(name: 'Enfeil Vacca')
System.create(name: 'Gaar')
System.create(name: 'Niushe')
System.create(name: 'Ophiuchi B 36')
System.create(name: 'Ophiuchi B 37')
System.create(name: 'Ophiuchi B 38')
System.create(name: 'I Theta Shaowei')
System.create(name: 'II Theta Shaowei')
System.create(name: 'Delta Pavonis')
System.create(name: 'Theta Shalish')
System.create(name: 'Epsilon Alangue')
System.create(name: 'Alpha Piscium')
System.create(name: 'Kirana Alef')
System.create(name: 'Krona Centa')
System.create(name: 'Beta Herculis')
System.create(name: 'Markona Prime')
System.create(name: 'Sirius A')
System.create(name: 'Sirius B')
System.create(name: 'Narádž')
System.create(name: 'Niazi')
System.create(name: 'Mettuli')
System.create(name: 'Camelopardalis')
System.create(name: 'Coma Berenices')
System.create(name: 'Hydra')
System.create(name: 'Epsilon Alangue')
System.create(name: 'Alfa Selestis')
System.create(name: 'Fornax')
System.create(name: 'Eridani A')
System.create(name: 'Rigel')
System.create(name: 'Risp Centra')
System.create(name: 'Leo Minor')
System.create(name: 'Microscopium')
System.create(name: 'Piscis Austrinus')
System.create(name: 'Salusa Centra')
System.create(name: 'Semba')
System.create(name: 'Virgo')
System.create(name: 'Ursa Minor')
System.create(name: 'Tulapin Centra')
System.create(name: 'Zabulon')
System.create(name: 'Taligari')
System.create(name: 'III Delta Kaising')
System.create(name: 'Revana Una')
System.create(name: 'Arana')
System.create(name: 'Septum I')
System.create(name: 'Septum II')
System.create(name: 'Alfa Centuri')
System.create(name: 'Triangulum Australe')
System.create(name: 'Galorn')
System.create(name: 'Lingora')
System.create(name: 'II Delta Kaising')
System.create(name: 'Zeta Olympus')
System.create(name: 'I Delta Kaising')
System.create(name: 'Delta Ferol ')
System.create(name: 'Aqua Una')
System.create(name: 'Corona Auatralis')
System.create(name: 'Thalim')
System.create(name: 'Yadin')
System.create(name: 'Titania')

p 'System done'

Planet.vytvor('Aclin', 'Aclin Neutra', 1)
Planet.vytvor('Aclin II', 'Aclin Neutra', 2)
Planet.vytvor('Al-Dhaneb', 'Delphinus', 1)
Planet.vytvor('Zamar', 'Delphinus', 2)
Planet.vytvor('Anbus I', 'Anbus', 1)
Planet.vytvor('Anbus II', 'Anbus', 2)
Planet.vytvor('Anbus III', 'Anbus', 3)
Planet.vytvor('Anbus IV', 'Anbus', 4)
Planet.vytvor('Andloy', 'Aclin Beta', 1)
Planet.vytvor('Arbelough', 'Eridani C', 1)
# Planet.vytvor('Arrakis', 'Mu Draconis', 1)
Planet::Arrakis.vytvor
p 'Arrakis done'
Planet.vytvor('Atar', 'Atari', 1)
Planet.vytvor('Atar II', 'Atari', 2)
Planet.vytvor('Atar III', 'Atari', 3)
Planet.vytvor('Atar IV', 'Atari', 4)
Planet.vytvor('Belner', 'Balút', 1)
Planet.vytvor('Balút', 'Balút', 2)
Planet.vytvor('Barandik', 'Barandik', 1)
Planet.vytvor('Bela Tegeuse I', 'Kuentsing', 1)
Planet.vytvor('Bela Tegeuse II', 'Kuentsing', 2)
Planet.vytvor('Bela Tegeuse III', 'Kuentsing', 3)
Planet.vytvor('Bela Tegeuse IV', 'Kuentsing', 4)
Planet.vytvor('Bela Tegeuse V', 'Kuentsing', 5)
Planet.vytvor('Biarek', 'Alastria', 1)
Planet.vytvor('Alastria', 'Alastria', 2)
Planet.vytvor('Bifkar', 'Norma Cenva', 1)
Planet.vytvor('Buzell', 'Buzell Alpha', 1)
Planet.vytvor('Beakkal', 'Beakkal Centa', 1)
Planet.vytvor('Danuun', 'Alpha Centauri A', 1)
Planet.vytvor('Dan', 'Alpha Centauri A', 2)
# Planet.vytvor('Caladan', 'Alpha Centauri A', 3)
Planet::Caladan.vytvor
p 'Caladan done'
Planet.vytvor('Letona', 'Alpha Centauri A', 4)
Planet.vytvor('Canidar I', 'Eridani B', 1)
Planet.vytvor('Canidar II', 'Eridani B', 2)
Planet.vytvor('Cerbol', 'Cerbol Leta', 1)
Planet.vytvor('Boreth', 'Cerbol Leta', 2)
Planet.vytvor('Danu I', 'Danu', 1)
Planet.vytvor('Danu II', 'Danu', 2)
Planet.vytvor('Danu III', 'Danu', 3)
Planet.vytvor('Danu IV', 'Danu', 4)
Planet.vytvor('Dur', 'Dur', 1)
Planet.vytvor('Habla', 'Alpha Centauri B', 1)
Planet.vytvor('Hufuf', 'Alpha Centauri B', 2)
Planet.vytvor('Ellaka', 'Alpha Centauri B', 3)
# Planet.vytvor('Ekaz', 'Alpha Centauri B', 4)
Planet.vytvor('Enfeil', 'Enfeil Vacca', 1)
Planet.vytvor('Enfeil Dabai', 'Enfeil Vacca', 2)
Planet.vytvor('Gaar I ', 'Gaar', 1)
Planet.vytvor('Gaar II', 'Gaar', 2)
Planet.vytvor('Gaar III', 'Gaar', 3)
Planet.vytvor('Gamont', 'Niushe', 3)
# Planet.vytvor('Grumman', 'Niushe', 2)
Planet.vytvor('Niusche', 'Niushe', 4)
# Planet.vytvor('Giedi Prima', 'Ophiuchi B 36', 1)
Planet::GiediPrima.vytvor
p 'Giedi Prima done'
Planet.vytvor('Sikun', 'Ophiuchi B 37', 2)
Planet.vytvor('Lampadas', 'Ophiuchi B 38', 3)
Planet.vytvor('Trobo', 'I Theta Shaowei', 1)
Planet.vytvor('Trina', 'I Theta Shaowei', 2)
Planet.vytvor('Gináz', 'I Theta Shaowei', 3)
Planet.vytvor('Hagal Deva', 'II Theta Shaowei', 1)
Planet.vytvor('Hagal Nocturna', 'II Theta Shaowei', 2)
Planet.vytvor('Hagal', 'II Theta Shaowei', 3)
Planet.vytvor('Pavonis II', 'Delta Pavonis', 2)
Planet.vytvor('Harmonthep', 'Delta Pavonis', 3)
# Planet.vytvor('Iks (Xuttuh)', 'Delta Pavonis', 10)
Planet.vytvor('Shalish I', 'Theta Shalish', 1)
Planet.vytvor('Shalish II', 'Theta Shalish', 2)
Planet.vytvor('Shalish III', 'Theta Shalish', 3)
Planet.vytvor('Chusúk', 'Theta Shalish', 4)
Planet.vytvor('Lernaeus', 'Theta Shalish', 5)
Planet.vytvor('Alangue I', 'Epsilon Alangue', 1)
Planet.vytvor('Alangue II', 'Epsilon Alangue', 2)
Planet.vytvor('Alangue III', 'Epsilon Alangue', 3)
Planet.vytvor('Alangue IV', 'Epsilon Alangue', 4)
Planet.vytvor('Kadiš', 'Epsilon Alangue', 5)
Planet.vytvor('Alangue VI ', 'Epsilon Alangue', 6)
Planet.vytvor('Alangue VII', 'Epsilon Alangue', 7)
Planet.vytvor('Korint', 'Alpha Piscium', 1)
# Planet.vytvor('Kaitan', 'Alpha Piscium', 2)
Planet::Kaitan.vytvor
p 'Kaitan done'
Planet.vytvor('Piscium', 'Alpha Piscium', 3)
Planet.vytvor('Kirana Alef I', 'Kirana Alef', 1)
Planet.vytvor('Kirana Alef II', 'Kirana Alef', 2)
Planet.vytvor('Kirana Alef III', 'Kirana Alef', 3)
Planet.vytvor('Kirana Alef IV', 'Kirana Alef', 4)
Planet.vytvor('Kronin', 'Krona Centa', 1)
Planet.vytvor('Herculis I', 'Beta Herculis', 1)
Planet.vytvor('Herculis II', 'Beta Herculis', 2)
Planet.vytvor('Herculis III', 'Beta Herculis', 3)
Planet.vytvor('Heculis IV', 'Beta Herculis', 4)
Planet.vytvor('Lankiveil', 'Beta Herculis', 5)
Planet.vytvor('Markon', 'Markona Prime', 1)
Planet.vytvor('Molitor', 'Sirius A', 1)
Planet.vytvor('Calibra', 'Sirius A', 2)
Planet.vytvor('Muritan', 'Sirius B', 1)
Planet.vytvor('Narádž I', 'Narádž', 1)
Planet.vytvor('Narádž II', 'Narádž', 2)
Planet.vytvor('Narádž III', 'Narádž', 3)
Planet.vytvor('Narádž VI', 'Narádž', 5)
Planet.vytvor('Narádž VI', 'Narádž', 7)
Planet.vytvor('Niazi', 'Niazi', 1)
Planet.vytvor('Niazi Dua', 'Niazi', 2)
Planet.vytvor('Novebruns', 'Mettuli', 3)
Planet.vytvor('Palma', 'Mettuli', 2)
Planet.vytvor('Parella', 'Camelopardalis', 1)
Planet.vytvor('Pilargo', 'Coma Berenices', 1)
Planet.vytvor('Ponciard', 'Hydra', 1)
Planet.vytvor('Alangue I', 'Epsilon Alangue', 1)
Planet.vytvor('Alangue II', 'Epsilon Alangue', 2)
Planet.vytvor('Poritrin', 'Epsilon Alangue', 3)
Planet.vytvor('Alangue IV', 'Epsilon Alangue', 4)
Planet.vytvor('Selestis', 'Alfa Selestis', 2)
Planet.vytvor('Reenol', 'Alfa Selestis', 1)
Planet.vytvor('Renditai', 'Fornax', 1)
Planet.vytvor('Eridani I', 'Eridani A', 1)
Planet.vytvor('Eridani II', 'Eridani A', 2)
Planet.vytvor('Eridani III', 'Eridani A', 3)
# Planet.vytvor('Riches', 'Eridani A', 4)
Planet.vytvor('Rigel I', 'Rigel', 1)
Planet.vytvor('Rigel II', 'Rigel', 2)
Planet.vytvor('Rigel III', 'Rigel', 3)
Planet.vytvor('Rigel IV', 'Rigel', 4)
Planet.vytvor('Rigel V', 'Rigel', 5)
Planet.vytvor('Rigel VI', 'Rigel', 6)
Planet.vytvor('Risp I', 'Risp Centra', 1)
Planet.vytvor('Risp II', 'Risp Centra', 2)
Planet.vytvor('Risp III', 'Risp Centra', 3)
Planet.vytvor('Risp IV', 'Risp Centra', 4)
Planet.vytvor('Risp V', 'Risp Centra', 5)
Planet.vytvor('Risp VI', 'Risp Centra', 6)
Planet.vytvor('Risp VII', 'Risp Centra', 7)
Planet.vytvor('Rocu', 'Leo Minor', 1)
Planet.vytvor('Minor', 'Leo Minor', 2)
Planet.vytvor('Horologium', 'Leo Minor', 3)
Planet.vytvor('Rom', 'Microscopium', 1)
Planet.vytvor('Lupus', 'Microscopium', 2)
Planet.vytvor('Musca', 'Microscopium', 3)
Planet.vytvor('Octans', 'Microscopium', 4)
Planet.vytvor('Rossak', 'Piscis Austrinus', 1)
Planet.vytvor('Salusa Primus', 'Salusa Centra', 1)
# Planet.vytvor('Salusa Secundus', 'Salusa Centra', 2)
Planet::SalusaSecundus.vytvor
p 'Salusa Secundus done'
Planet.vytvor('Semba I', 'Semba', 1)
Planet.vytvor('Semba II', 'Semba', 2)
Planet.vytvor('Semba III', 'Semba', 3)
Planet.vytvor('Semba IV', 'Semba', 4)
Planet.vytvor('Seprek', 'Virgo', 1)
Planet.vytvor('Vela', 'Virgo', 2)
Planet.vytvor('Tarahell', 'Ursa Minor', 1)
Planet.vytvor('Tulapin I', 'Tulapin Centra', 1)
Planet.vytvor('Tulapin II', 'Tulapin Centra', 2)
Planet.vytvor('Tulapin III', 'Tulapin Centra', 3)
Planet.vytvor('Tulapin IV', 'Tulapin Centra', 4)
# Planet.vytvor('Tulapin V', 'Tulapin Centra', 5) Renegati
Planet::Tulapin.vytvor
p 'Tulapin done'
Planet.vytvor('Zabulon I', 'Zabulon', 1)
Planet.vytvor('Zabulon II', 'Zabulon', 2)
Planet.vytvor('Zabulon III', 'Zabulon', 3)
Planet.vytvor('Zabulon IV', 'Zabulon', 4)
Planet.vytvor('Zabulon V', 'Zabulon', 5)
Planet.vytvor('Zanovar', 'Taligari', 2)
Planet.vytvor('Kaising I', 'III Delta Kaising', 1)
Planet.vytvor('Kaising II', 'III Delta Kaising', 2)
Planet.vytvor('Chonsu I', 'Revana Una', 1)
Planet.vytvor('Chonsu II', 'Revana Una', 2)
Planet.vytvor('Revana', 'Revana Una', 3)
Planet.vytvor('Arana I', 'Arana', 1)
Planet.vytvor('Arana II', 'Arana', 2)
Planet.vytvor('Himaltar', 'Arana', 3)
Planet.vytvor('Alara I', 'Septum I', 1)
Planet.vytvor('Alara II', 'Septum I', 2)
Planet.vytvor('Alara III', 'Septum I', 3)
Planet.vytvor('Alara IV', 'Septum I', 4)
Planet.vytvor('Alara V', 'Septum I', 5)
Planet.vytvor('Alara VI', 'Septum I', 6)
Planet.vytvor('Alara VII', 'Septum I', 7)
Planet.vytvor('Aralon', 'Septum II', 1)
Planet.vytvor('Barinx', 'Septum II', 2)
Planet.vytvor('Centuri I', 'Alfa Centuri', 1)
Planet.vytvor('Centuri II', 'Alfa Centuri', 2)
Planet.vytvor('Dallar', 'Triangulum Australe', 1)
Planet.vytvor('Falkan', 'Triangulum Australe', 2)
Planet.vytvor('Wallach III', 'Triangulum Australe', 3)
Planet.vytvor('Wallach IV', 'Triangulum Australe', 4)
Planet.vytvor('Wallach V', 'Triangulum Australe', 5)
Planet.vytvor('Wallach VI ', 'Triangulum Australe', 6)
Planet.vytvor('Drebin', 'Triangulum Australe', 7)
Planet.vytvor('Wallach VIII', 'Triangulum Australe', 8)
Planet.vytvor('Wallach IX', 'Triangulum Australe', 9)
Planet.vytvor('Galorn', 'Galorn', 1)
Planet.vytvor('Kliban', 'Galorn', 2)
Planet.vytvor('Nytet', 'Galorn', 3)
Planet.vytvor('Lingora', 'Lingora', 1)
Planet.vytvor('Huwi I', 'II Delta Kaising', 1)
Planet.vytvor('Huwi II', 'II Delta Kaising', 2)
Planet.vytvor('Zeta Dian', 'Zeta Olympus', 1)
Planet.vytvor('Olymp', 'Zeta Olympus', 2)
Planet.vytvor('Zeta II', 'Zeta Olympus', 3)
Planet.vytvor('Zeta III', 'Zeta Olympus', 4)
Planet.vytvor('Solten', 'I Delta Kaising', 1)
Planet.vytvor('Circinus', 'I Delta Kaising', 2)
Planet.vytvor('Saos', 'Delta Ferol ', 1)
Planet.vytvor('Ferrol', 'Delta Ferol ', 2)
Planet.vytvor('Ferrol Uno', 'Delta Ferol ', 3)
Planet.vytvor('Ferrol Dia', 'Delta Ferol ', 4)
Planet.vytvor('Heimidal', 'Aqua Una', 1)
Planet.vytvor('Cebotea', 'Aqua Una', 2)
Planet.vytvor('Largamenia', 'Aqua Una', 3)
Planet.vytvor('Revagon', 'Aqua Una', 4)
Planet.vytvor('Unitera I', 'Corona Auatralis', 1)
Planet.vytvor('Unitera II', 'Corona Auatralis', 2)
Planet.vytvor('Unitera III', 'Corona Auatralis', 3)
Planet.vytvor('Unitera IV', 'Corona Auatralis', 4)
Planet.vytvor('Tleilax', 'Thalim', 1)
Planet.vytvor('Washuun', 'Thalim', 2)
Planet.vytvor('Yandin I', 'Yadin', 1)
Planet.vytvor('Yandin II', 'Yadin', 2)
Planet.vytvor('Yandin III', 'Yadin', 3)
Planet.vytvor('Yandin IV', 'Yadin', 4)
Planet.vytvor('Yandin V', 'Yadin', 5)
Planet.vytvor('Yandin VI', 'Yadin', 6)
Planet.vytvor('Yandin VII', 'Yadin', 7)
Planet.vytvor('Yandin VIII', 'Yadin', 8)
Planet.vytvor('Yandin IX', 'Yadin', 9)
Planet::Titania.vytvor

p 'Planet done'